### ISSUE TITLE
Gauss Barrel doesn't stay on for the full duration

### ISSUE THREAD

**Issue by NaesKun** [0ceal0t/SkillSwap#3]
I want the old Gauss Barrel VFX to replace the current Hypercharge. The VFX is replaced properly, but the Gauss Barrel doesn't stay on the end of the gun and just disappears. I want the Gauss Barrel to stay on the end of the gun for the full duration of Overheat. Can this tool help me do this? If not, are there other modding resources I can do to accomplish this?

**Comment by 0ceal0t** [comment]
I see. That's annoying that it just disappears. For some context, what SkillSwap does is replace a skills `.tmb` file, which is what determines which animations/vfxs to play. If you want to extend the duration, you might need to modify that file. Unfortunately, the actual format of the `.tmb` files is extremely poorly understood, so I can't offer much help there.

**Comment by 0ceal0t** [comment]
also, I might have been wrong about gauss barrel not being a vfx. So it may be worth testing extending the duration of the vfx. Here's how you'd do that:
1. make sure you have the SkillSwap mod that swaps hypercharge and gauss barrel still installed
2. using VFX editor, open Gauss Barrel 1 as both the "source" and "preview on"
3. edit the the particles and emitters (specficially, I'd recommend looking at emitters>animation>life, particles>animation>life, and particles>animation>scale)
4. click "update" and try using hypercharge
5. if it works, you can then export the vfx mod

![image](https://user-images.githubusercontent.com/18051158/140655339-3999059c-0cd7-44bf-a34b-337676ec21ed.png)
![image](https://user-images.githubusercontent.com/18051158/140655361-deecf6ba-e4f5-4d3b-84ba-33829bcd1f75.png)

**Comment by 0ceal0t** [comment]
some miscellaneous notes about the vfx:
- Gauss barrel is located in the "non-player actions" section since you can no longer technically use it during normal play
- You can also try extending the duration of the item in the "Timelines" section
- Why I mentioned particles>animation>scale is because it looks like particle 6 is scaled down significantly after a sort duration (making it basically invisible)

![image](https://user-images.githubusercontent.com/18051158/140655606-fbda8c9f-c4d4-41eb-8079-0b603cd72d29.png)

**Comment by NaesKun** [comment]
Aha, this was what I was looking for. Now we're getting somewhere. I'll close this issue and reopen the other one to ask a few more questions.
