### ISSUE TITLE
Primal Rend (WAR) to Plunge (DRK)

### ISSUE THREAD

**Issue by VanitasDecay** [0ceal0t/SkillSwap#9]
Hey, Ocealot!
First of all I would like to thank you for the plugins, you did a great job.

So, I know we've been warned more than once not to mess with movement actions, but I have to ask. I would very much like to replace the animation from DRK's Plunge action to WAR's Primal Rent, both actions have the same range (20y), how could that go wrong? As this tool only changes the animations, we would be ignoring the only difference between them, which would be the 5y radius that Primal Rend has because it is an AoE.

**Comment by 0ceal0t** [comment]
movement abilities are locked off because a lot of knockback and animation lock stuff is clientside, so you could potentially make changes that weren't just cosmetic, but detectable. Your specific use case probably would be fine, but in the interest of prevent people from doing stupid things, movement abilities will remain off-limits
